/*
 * File: app/view/ApplicationViewport.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LocalPagingDemo.view.ApplicationViewport', {
    extend: 'Ext.container.Viewport',

    layout: {
        type: 'fit'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    title: 'Demo Grid',
                    store: 'LocalPagingStore',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'col1',
                            flex: 1,
                            text: 'Column 1'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'col2',
                            flex: 1,
                            text: 'Column 2'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'col3',
                            flex: 1,
                            text: 'Column 3'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'col4',
                            flex: 1,
                            text: 'Column 4'
                        }
                    ],
                    viewConfig: {

                    },
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            displayInfo: true,
                            store: 'LocalPagingStore',
                            dock: 'bottom'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});